### PR TITLE
Refactor game loop to allow easy external use

### LINKED ISSUE #8: Thoughts on driving the play loop externally?
I had a wild idea that I'd like to try to hook up the scottkit play code to a slack bot so you could play it via chat. I've played around with trying to treat it as a shell script and work at the stdin/stdout level but turned into a pretty big PITA. I went in and stripped the binary down to just:
```rb
require 'scottkit/game'

file_name = 'game.sao'
options = {}
game = ScottKit::Game.new(options)
game.load(IO.read(file_name))
game.decompile(StringIO.new)
game.play
```
I think I can just use an `StringIO` with `$stdout` to capture the output, clearing it between turns... though I suspect I'll add `puts` and `print` methods that target my buffer so I don't have to worry about anything else logging to the global variable. 

But I'm not sure quite how to handle the input. The `play` method's loop calls into the `gets` method so that seems like a pretty obvious place to hook in. I'm wondering if it'd be feasible to fiber to pipe the input from the slack messages to the game. `gets` would call `thread.resume` and wait for input then when slack got something it could call `yield` to send it across.

Any thoughts?

### PR DESCRIPTION
**Pull request by drewish**
This "Fixes #8" but is really just a conversation starter. It's currently rebased on #15 so we can ensure the specs pass.

Here's the hacky script I'm using so you can get and idea of how the input and output are handled:
```rb
require 'slack-ruby-client'
require 'scottkit/game'

# The game sends it output to stdout but we just capture the strings in a buffer
# and pull them out as chunks which we send in a single message. We ignore the
# play method since it blocks on `gets` and just call some methods directly.
class MyGame < ScottKit::Game
  attr_reader :output_buffer

  def initialize(options)
    @output_buffer = StringIO.new
    super
  end

  def puts *args
    output_buffer.puts *args
  end

  def print *args
    output_buffer.print *args
  end

  # Grab all the output and reset the buffer
  def prompt_for_turn
    super

    string = output_buffer.string
    output_buffer.reopen('')
    string
  end
end

Slack.configure do |config|
  config.token = ENV['SLACK_API_TOKEN']
  config.logger = Logger.new(STDOUT)
  config.logger.level = Logger::INFO
end

client = Slack::RealTime::Client.new
channel = nil

file_name = 'game.sao'
game = MyGame.new(output_buffer: StringIO.new)
game.load(IO.read(file_name))
game.decompile(StringIO.new)

client.on :hello do
  puts "Successfully connected, welcome '#{client.self.name}' to the '#{client.team.name}' team at https://#{client.team.domain}.slack.com."

  # Limit the conversation to one channel for now
  channel = client.channels.values.find { |c| c.name == 'bots' }

  game.prepare_to_play
  client.message channel: channel['id'], text: game.prompt_for_turn
end

client.on :message do |data|
  next if data.channel != channel['id']
  # TODO: Figure out what do do about starting a new game
  next if game.finished?

  client.typing channel: data.channel

  game.process_turn(data.text)
  client.message channel: data.channel, text: game.prompt_for_turn
end

client.on :close do |_data|
  puts "Client is about to disconnect"
end

client.on :closed do |_data|
  puts "Client has disconnected successfully!"
end

client.start_async

loop do
  Thread.pass
end
```

### CODE REVIEW

**Comment by drewish** [comment]
I went ahead and put that up at https://github.com/drewish/scottbot I'll work on getting a proper readme in there to make it a little clearer how to get it up and running.

**Comment by MikeTaylor** [comment]
It's nice to see this progressing. The changes to ScottKit itself are obviously benign, and I will merge them momentarily. A couple of questions about your client code, though ...

* Why does `MyGame` need to be a subclass of `ScottKit::Game`? So far as I can see, it merely uses stuff _from_ a `ScottKit::Game`, so delegation seems more appropriate than inheritance?

* Why do you call `game.decompile(StringIO.new)`?

**Comment by drewish** [comment]
The only reason I'm subclassing at this point is to replace `$stdout` with my object. We could make that an option that defaults to the current value. 

Good note on the `decompile`. I think it was copy pasta'ed from the play method in the binary that runs from source. I'd switched to an .sao at some point and never removed it.

**Comment by MikeTaylor** [comment]
I was going to say "the only reason _ever_ to call decompile is if you want to get a SCK". But I see from my own `bin/scottkit` that that's not quite true:
```
def play(game)
  # Decompile (and discard result) to get entity names resolved in
  # right order.  This ensures that debugging output that uses these
  # names will use them in the same way as decompiler output.
  dummy = StringIO.new
  game.decompile(dummy)
  game.play
end
```

**Comment by drewish** [comment]
Right, that's exactly where I'd gotten it. I didn't realize it still came into play with the compiled files as well.

**Comment by MikeTaylor** [comment]
Well, it doesn't really. I should wrap that use. New issue incoming.

**Comment by drewish** [comment]
Just a note that this isn't capturing output from instructions so output from actions that call print will be lost. #32 starts to address this issue.

**Pull request merged**
